<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>interview.guide</groupId>
        <artifactId>interview-guide</artifactId>
        <version>0.0.1-SNAPSHOT</version>
        <relativePath>../pom.xml</relativePath>
    </parent>
    <artifactId>bootstrap</artifactId>
    <name>bootstrap</name>

    <dependencies>
        <!-- platform base -->
        <dependency>
            <groupId>interview.guide</groupId>
            <artifactId>common</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>interview.guide</groupId>
            <artifactId>api</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>interview.guide</groupId>
            <artifactId>framework</artifactId>
            <version>${project.version}</version>
        </dependency>

        <!-- business modules -->
        <dependency>
            <groupId>interview.guide</groupId>
            <artifactId>bportal</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>interview.guide</groupId>
            <artifactId>cportal</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>interview.guide</groupId>
            <artifactId>admin</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>interview.guide</groupId>
            <artifactId>engine</artifactId>
            <version>${project.version}</version>
        </dependency>

        <dependency>
            <groupId>interview.guide</groupId>
            <artifactId>system</artifactId>
            <version>${project.version}</version>
        </dependency>
    </dependencies>
</project>
