package interview.common.enums;

import lombok.Getter;

/**
 * @author zhuxi
 * @apiNote 错误码枚举类
 */
@Getter
public enum ErrorCode {

    // ------------ 10xxx 系统/全局级错误码 ------------
    SUCCESS(10000, "成功"),
    SYSTEM_ERROR(500, "系统错误或繁忙,请稍后重试或联系客服"),
    SERVICE_UNAVAILABLE(503, "服务不可用"),
    TOO_MANY_REQUESTS(429, "请求过于频繁"),
    PARAM_VALID_ERROR(10001, "参数校验失败"),
    INTERFACE_NOT_FOUND(404, "接口不存在"),
    METHOD_NOT_ALLOWED(405, "请求方法不允许"),
    REQUEST_BODY_OVERFLOW(413, "请求实体过大"),
    NOT_SUPPORTED_MEDIA_TYPE(415, "不支持的媒体类型"),
    REQUEST_TIMEOUT(408, "请求超时"),
    DATA_TYPE_ERROR(10002, "数据类型错误"),
    OBJECT_TO_JSON_ERROR(10003, "JSON 序列化错误"),
    JSON_TO_OBJECT_ERROR(10004, "JSON 反序列化错误"),
    TRACE_ID_MISSING(10005, "服务端未能建立调用链 ID"),
    ENCRYPTION_ERROR(10006, "加密失败"),
    DECRYPTION_ERROR(10007, "解密失败"),
    FILE_UPLOAD_FAILED(10008, "文件上传失败,请稍后重试或联系客服"),
    FILE_DOWNLOAD_FAILED(10009, "文件下载失败"),
    FILE_READ_FAILED(10010,"文件读取失败"),
    INVALID_FILENAME(10011,"文件名为空或不规范"),
    FILE_DELETE_FAILED(10012,"文件删除失败"),
    PAGE_PARAM_INVALID(10013, "分页参数不合法"),
    SORT_FIELD_INVALID(10014, "不支持的排序字段"),
    SORT_DIRECTION_INVALID(10015, "排序方向仅支持 asc 或 desc"),
    TIME_FORMAT_INVALID(10016, "时间必须使用带时区的 ISO-8601 格式"),
    TIME_RANGE_INVALID(10017, "开始时间不能晚于结束时间"),


    // ------------ 20xxx 用户认证与授权错误码 ------------
    USER_NOT_LOGIN(401, "未登录"),
    TOKEN_EXPIRED(401, "Token 已过期"),
    TOKEN_INVALID(401, "Token 无效"),
    PERMISSION_DENIED(403, "权限不足"),
    USER_ALREADY_FREEZE(403, "用户已冻结"),
    RISK_CONTROL(403, "你的账户当前存在异常，请等待稍后重试或联系客服"),
    CODE_ERROR(20001, "验证码错误"),
    CODE_EXPIRED(20002, "验证码已过期"),
    CODE_ERROR_OR_EXPIRED(20010, "验证码错误或已过期"),
    PHONE_ALREADY_EXISTS(20003, "手机号已注册"),
    THIRD_PARTY_AUTH_ERROR(20004, "第三方授权失败"),
    PASSWORD_STRENGTH_ERROR(20005, "密码强度不够"),
    USERNAME_ALREADY_EXISTS(20006, "用户名已存在"),
    EMAIL_ALREADY_EXISTS(20007, "邮箱已注册"),
    REFRESH_TOKEN_EXPIRED(20008, "Refresh Token 已过期，请重新登录"),
    REFRESH_TOKEN_REVOKED(20009, "Refresh Token 已被撤销"),
    DEVICE_LIMIT_EXCEEDED(20018, "登录设备数量超过限制"),
    USER_NOT_FOUND(20011, "用户不存在"),
    PASSWORD_ERROR(20012, "密码错误"),
    ACCOUNT_DISABLED(20013, "账号已被禁用"),
    CODE_ONE_MINUTE(20014, "验证码已经发送，请 1 分钟后再试"),
    ACCOUNT_DATA_ANOMALY(20015, "账号数据状态异常，请稍后重试或联系客服"),
    ROLE_ALREADY_ASSIGNED(20016, "角色已分配给该用户"),
    NOT_YOUR_PHONE(20017, "请使用绑定的手机号！"),
    NO_VERIFY_TOKEN(20020,"缺少安全操作授权,请完成手机号验证获取授权"),
    VERIFY_TOKEN_EXPIRE(20021,"安全身份凭证已过期，请重新进行手机验证"),
    SECURE_ACTION_NOT_MATCH(20023,"安全操作令牌不适用于当前操作"),
    ROLE_NOT_EXIST(20025,"该角色不存在"),
    NO_ALLOW_ROLE(20026,"只能分配对应域的角色"),
    SMS_TYPE_NOT_ALLOWED(20031,"当前接口不支持该短信类型"),
    SECURE_CHALLENGE_INVALID(20032,"安全验证任务无效或已过期"),
    SECURE_CHALLENGE_STATE_INVALID(20033,"安全验证任务状态不允许当前操作"),
    SECURE_CHALLENGE_ATTEMPTS_EXCEEDED(20034,"验证码错误次数过多，请重新发起安全验证"),

    // ------------ 30xxx 企业/多租户错误码 ------------
    ENTERPRISE_NOT_FOUND(30001, "企业不存在"),
    ENTERPRISE_FROZEN(30002, "企业已被冻结"),
    ENTERPRISE_NOT_CERTIFIED(30003, "企业未通过资质认证"),
    ENTERPRISE_MEMBER_LIMIT(30004, "企业成员数量已达上限"),
    ENTERPRISE_MEMBER_NOT_FOUND(30005, "企业成员不存在"),
    ENTERPRISE_ALREADY_EXISTS(30006, "企业已存在"),
    NOT_ENTERPRISE_OWNER(30007, "非企业所有者，无权操作"),
    ENTERPRISE_MEMBER_ALREADY_EXISTS(30008, "该用户已是企业成员"),
    ENTERPRISE_TENANT_MISMATCH(30009, "租户隔离校验不通过"),
    ENTERPRISE_DATA_ANOMALY(30010, "企业数据异常，请联系客服"),
    ENTERPRISE_NAME_ALREADY_EXISTS(30011, "企业名称已存在"),
    ENTERPRISE_NOT_BELONG(30012,"用户不属于该企业"),
    SECURE_TOKEN_INVALID(30013, "安全操作令牌无效或已过期"),
    SECURE_TOKEN_USER_MISMATCH(30014, "安全操作令牌与当前用户不匹配"),
    CONTACT_VERIFY_FLOW_INVALID(30015, "企业联系电话验证流程无效或已过期"),
    CONTACT_VERIFY_STATE_INVALID(30016, "企业联系电话验证流程状态不允许当前操作"),
    ENTERPRISE_CONTACT_CHANGED(30017, "企业联系电话已发生变化，请重新验证"),
    PHONE_SAME_AS_OLD(30018, "新联系电话不能与原联系电话相同"),
    MEMBER_ALREADY_EXISTS(20027,"用户已在企业中"),
    NO_OPERATE_ENTERPRISE_OWNER(20028,"不能操作企业所有人"),
    NO_DELETE_OWNER(20029,"不能移除自己"),
    CURREMT_USER_NOT_ENTERPRISE_MEMBER(20030,"当前登录账户不属于该企业成员"),


    // ------------ 40xxx 岗位/简历/候选人错误码 ------------
    JOB_NOT_FOUND(40001, "岗位不存在"),
    JOB_ALREADY_CLOSED(40002, "岗位已关闭"),
    JOB_NOT_BELONG_TO_ENTERPRISE(40003, "岗位不属于当前企业"),
    RESUME_NOT_FOUND(40004, "简历不存在"),
    RESUME_ANALYSIS_FAILED(40005, "简历 AI 解析失败,请稍后重试或联系客服"),
    RESUME_FILE_TYPE_NOT_SUPPORTED(40006, "不支持的简历文件格式"),
    RESUME_FILE_TOO_LARGE(40007, "简历文件过大"),
    RESUME_DUPLICATE_HASH(40008, "重复的简历文件"),
    CANDIDATE_NOT_FOUND(40009, "候选人不存在"),
    JOB_APPLICATION_ALREADY_EXISTS(40010, "已投递该岗位，请勿重复投递"),
    JOB_APPLICATION_STATUS_INVALID(40011, "投递记录状态不合法"),
    RESUME_ANALYSIS_NOT_FOUND(40012, "简历分析结果不存在"),
    CANDIDATE_PROFILE_NOT_FOUND(40013, "候选人画像不存在"),
    APPLICATION_NOT_FOUND(40014, "投递记录不存在"),
    FILE_SIZE_TOO_LARGE_OR_EMPTY(40015,"上传文件为空或者过大(>10MB)"),
    FILE_IS_EXISTS(40016,"文件已存在"),
    RESUME_IS_NOT_YOUR(40017,"请投递自己的简历"),
    RESUME_MOST_IS_FIVE(40019,"简历最多只能有5份,请先删除一份，再上传简历"),
    JOB_VERSION_CONFLICT(40020,"岗位已被其他请求修改，请刷新后重试"),
    IDEMPOTENCY_KEY_CONFLICT(40021,"请勿重复操作"),
    RESUME_ANALYZE_STATUS_ERROR(40022,"简历状态异常或AI解析失败，请稍后重试或联系客服"),
    CANDIDATE_PROFILE_STATUS_INVALID(40023,"人才画像状态不允许当前操作"),
    CANDIDATE_PROFILE_GENERATION_FAILED(40024,"人才画像生成失败，请稍后重试"),
    JOB_SCREENING_CONFIG_NOT_FOUND(40025,"岗位 AI 初筛配置不存在"),
    JOB_SCREENING_CONFIG_VERSION_CONFLICT(40026,"岗位 AI 初筛配置已被修改，请刷新后重试"),
    APPLICATION_AI_SCREENING_NOT_FOUND(40027,"AI 初筛记录不存在"),
    APPLICATION_AI_SCREENING_STATUS_INVALID(40028,"AI 初筛状态不允许当前操作"),
    APPLICATION_AI_SCREENING_ALREADY_REVIEWED(40029,"AI 初筛结果已被审核"),
    CANDIDATE_JOB_MATCH_NOT_FOUND(40030,"岗位适配预测记录不存在"),
    CANDIDATE_JOB_MATCH_FAILED(40031,"岗位适配预测失败，请稍后重试"),
    CANDIDATE_JOB_MATCH_STATUS_INVALID(40032,"当前岗位适配预测状态不允许该操作"),
    JOB_APPLICATION_NOT_FOUND(40033,"岗位投递记录不存在"),

    // ------------ 50xxx 文本/面试流程错误码 ------------
    INTERVIEW_SCHEDULE_NOT_FOUND(50001, "面试排期不存在"),
    INTERVIEW_SCHEDULE_STATUS_INVALID(50002, "面试排期状态不合法"),
    INTERVIEW_SESSION_NOT_FOUND(50003, "面试会话不存在"),
    INTERVIEW_SESSION_ALREADY_COMPLETED(50004, "面试会话已结束"),
    INTERVIEW_ANSWER_NOT_FOUND(50005, "面试作答记录不存在"),
    INTERVIEW_TEMPLATE_NOT_FOUND(50006, "面试阶段模板不存在"),
    INTERVIEW_PHASE_CONFIG_NOT_FOUND(50007, "面试阶段配置不存在"),
    INTERVIEW_REPORT_NOT_FOUND(50008, "面试报告不存在"),
    INTERVIEW_TIME_CONFLICT(50009, "面试时间冲突"),
    INTERVIEW_ALREADY_IN_PROGRESS(50010, "面试正在进行中"),
    INTERVIEW_FLOW_NOT_ALLOWED(50011, "当前状态不允许该流转操作"),
    INTERVIEW_WORKFLOW_LOG_NOT_FOUND(50012, "流转日志不存在"),
    INTERVIEW_STAGE_TEMPLATE_NOT_FOUND(50013,"面试阶段模板不存在"),
    INTERVIEW_STAGE_TEMPLATE_NOT_YOUR_ENTERPRISE(50014,"面试阶段模板不属于当前企业"),
    INTERVIEW_TIME_INVALID(50015,"面试时间无效"),
    INTERVIEW_PLAN_DRAFT_NOT_FOUND(50018,"面试编排草案不存在"),
    CANDIDATE_INTERVIEW_AVAILABILITY_VERSION_CONFLICT(50021,"可面试时间已被修改，请刷新后重试"),
    CANDIDATE_INTERVIEW_AVAILABILITY_INVALID(50022,"可面试时间无效或存在重叠"),
    INTERVIEW_SCHEDULE_ALREADY_TERMINATED(50023,"面试正在进行或已经结束"),
    INTERVIEW_SCHEDULE_VERSION_CONFLICT(50024,"面试排期版本冲突"),
    INTERVIEW_SCHEDULE_NOT_YOUR_ENTERPRISE(50025,"面试排期不属于当前企业"),
    INTERVIEW_ROUND_CONFLICT(50026,"该轮面试已存在"),
    INTERVIEW_ROUND_NOT_DEFINED(50027,"该轮次不属于当前面试模板"),
    INTERVIEW_ROUND_SEQUENCE_INVALID(50028,"面试轮次必须按模板顺序连续创建"),
    INTERVIEW_TEMPLATE_MISMATCH(50029,"同一投递不能混用面试模板"),
    INTERVIEW_TEMPLATE_ALREADY_EXISTS(50030,"同名面试模板已存在"),
    INTERVIEW_TEMPLATE_VERSION_CONFLICT(50031,"面试模板已被修改，请刷新后重试"),
    INTERVIEW_TEMPLATE_STAGE_INVALID(50032,"面试模板阶段编码或顺序无效"),
    INTERVIEW_PHASE_CONFIG_VERSION_CONFLICT(50033,"阶段组卷配置已被修改，请刷新后重试"),

    // ------------ 60xxx 计费/钱包错误码 ------------
    SKU_NOT_FOUND(60001, "套餐 SKU 不存在"),
    SKU_NOT_ACTIVE(60002, "套餐已下架"),
    WALLET_NOT_FOUND(60003, "钱包不存在"),
    INSUFFICIENT_BALANCE(60004, "算力余额不足"),
    INSUFFICIENT_FROZEN_BALANCE(60005, "冻结余额不足"),
    PAYMENT_ORDER_NOT_FOUND(60006, "订单不存在"),
    PAYMENT_ORDER_EXPIRED(60007, "订单已过期"),
    PAYMENT_ORDER_ALREADY_PAID(60008, "订单已支付"),
    TOKEN_CONSUME_LOG_FAILED(60009, "算力消耗记录失败"),
    WALLET_VERSION_CONFLICT(60010, "钱包并发更新冲突，请重试"),
    BILLING_DISABLED(60011, "计费系统暂未启用"),
    WALLET_TRANSACTION_FAILED(60012, "钱包流水记录失败"),

    // ------------ 70xxx 语音面试错误码 ------------
    VOICE_SESSION_NOT_FOUND(70001, "语音会话不存在"),
    VOICE_SESSION_ALREADY_COMPLETED(70002, "语音会话已结束"),
    VOICE_MESSAGE_NOT_FOUND(70003, "语音消息不存在"),
    VOICE_EVALUATION_NOT_FOUND(70004, "语音评估结果不存在"),
    ASR_RECOGNITION_FAILED(70005, "语音识别失败"),
    TTS_SYNTHESIS_FAILED(70006, "语音合成失败"),
    VOICE_SESSION_STATUS_INVALID(70007, "语音会话状态不合法"),

    // ------------ 80xxx 代码沙箱错误码 ------------
    CODE_QUESTION_NOT_FOUND(80001, "编程题目不存在"),
    CODE_TEST_CASE_NOT_FOUND(80002, "测试用例不存在"),
    CODE_SUBMISSION_NOT_FOUND(80003, "代码提交记录不存在"),
    CODE_SUBMISSION_RESULT_NOT_FOUND(80004, "代码执行结果不存在"),
    CODE_EXECUTION_TIMEOUT(80005, "代码执行超时"),
    CODE_EXECUTION_MEMORY_LIMIT(80006, "代码执行内存超限"),
    CODE_EXECUTION_ERROR(80007, "代码执行异常"),
    CODE_LANGUAGE_NOT_SUPPORTED(80008, "不支持的编程语言"),
    CODE_SANDBOX_UNAVAILABLE(80009, "代码沙箱服务不可用"),
    CODE_REVIEW_FAILED(80010, "AI 代码审查失败"),

    // ------------ 90xxx 知识库/RAG 错误码 ------------
    KNOWLEDGE_BASE_NOT_FOUND(90001, "知识库文档不存在"),
    KNOWLEDGE_BASE_VECTORIZE_FAILED(90002, "知识库向量化失败"),
    DOCUMENT_CHUNK_NOT_FOUND(90003, "文档切片不存在"),
    RAG_SESSION_NOT_FOUND(90004, "RAG 会话不存在"),
    RAG_MESSAGE_NOT_FOUND(90005, "RAG 消息不存在"),
    KNOWLEDGE_BASE_FILE_TOO_LARGE(90006, "知识库文件过大"),
    KNOWLEDGE_BASE_DUPLICATE_HASH(90007, "知识库重复文件"),
    KNOWLEDGE_BASE_FILE_TYPE_NOT_SUPPORTED(90008, "不支持的文档格式"),

    // ------------ 100xxx 风控/合规/KYC 错误码 ------------
    KYC_NOT_FOUND(100001, "实名认证记录不存在"),
    KYC_NOT_PASSED(100002, "实名认证未通过"),
    KYC_ALREADY_SUBMITTED(100003, "已提交实名认证，请勿重复提交"),
    ENTERPRISE_CERT_NOT_FOUND(100004, "企业认证记录不存在"),
    ENTERPRISE_CERT_NOT_PASSED(100005, "企业资质认证未通过"),
    SENSITIVE_WORD_DETECTED(100006, "内容包含敏感词"),
    ANTI_CHEAT_EVENT_DETECTED(100007, "检测到异常行为"),
    USER_API_POLICY_BLOCKED(100008, "您的访问已被策略拦截"),
    RATE_LIMIT_EXCEEDED(100009, "请求频率超过限制"),
    USER_IN_BLACKLIST(100010, "您已被加入黑名单"),

    // ------------ 110xxx 消息通知/日志错误码 ------------
    NOTIFICATION_SEND_FAILED(110001, "消息通知发送失败"),
    NOTIFICATION_NOT_FOUND(110002, "通知消息不存在"),
    API_LOG_ARCHIVE_FAILED(110003, "日志归档失败"),

    // ------------ 120xxx AI/大模型错误码 ------------
    AI_PROVIDER_NOT_FOUND(120001, "AI 供应商不存在"),
    AI_PROVIDER_DISABLED(120002, "AI 供应商已被禁用"),
    AI_API_KEY_INVALID(120003, "AI API Key 已失效"),
    AI_MODEL_NOT_FOUND(120004, "AI 模型不存在"),
    AI_RESPONSE_PARSE_ERROR(120005, "AI 响应解析失败"),
    AI_SERVICE_TIMEOUT(120006, "AI 服务响应超时"),
    AI_SERVICE_UNAVAILABLE(120007, "AI 服务暂不可用"),
    AI_EMBEDDING_FAILED(120008, "向量化失败"),
    AI_GLOBAL_ROUTE_NOT_FOUND(120009, "AI 全局默认路由不存在"),
    AI_CONTENT_FILTERED(120010, "AI 输出内容被安全策略过滤"),
    AI_TOKEN_LIMIT_EXCEEDED(120011, "AI 上下文长度超过限制"),
    AI_SAFETY_GUARDRAIL_TRIGGERED(120012, "AI 安全护栏触发"),
    AI_PROVIDER_ALREADY_EXISTS(120013, "AI Provider ID 已存在"),
    AI_PROVIDER_VERSION_CONFLICT(120014, "AI Provider 配置版本冲突，请刷新后重试"),
    AI_PROVIDER_IN_USE(120015, "AI Provider 正被有效路由使用"),
    AI_PROVIDER_CONNECTION_FAILED(120016, "AI Provider 连接测试失败"),
    AI_GLOBAL_ROUTE_VERSION_CONFLICT(120017, "AI 全局默认路由版本冲突，请刷新后重试"),
    AI_SCENE_NOT_FOUND(120018, "AI 场景不存在"),
    AI_SCENE_VERSION_CONFLICT(120019, "AI 场景配置版本冲突，请刷新后重试"),
    AI_SCENE_PARAM_UNSUPPORTED(120020, "AI 场景参数或模型能力不支持"),
    AI_PROVIDER_TYPE_MISMATCH(120021, "AI Provider 模型类型与路由或场景配置不匹配"),
    AI_PROVIDER_TEST_UNSUPPORTED(120022, "当前模型类型暂不支持连接测试"),

    // ------------ 13xxx Spark 离线任务错误码 ------------
    SPARK_TASK_NOT_FOUND(130001, "Spark 任务不存在"),
    SPARK_TASK_STATUS_INVALID(130002, "Spark 任务状态不合法"),
    SPARK_TASK_EXECUTION_FAILED(130003, "Spark 任务执行失败"),

    // ------------ 14xxx 本地消息管理错误码 ------------
    LOCAL_MESSAGE_NOT_FOUND(140001, "本地消息不存在"),
    LOCAL_MESSAGE_STATUS_INVALID(140002, "本地消息状态不合法，仅允许重试 FAILED 状态的消息"),
    LOCAL_MESSAGE_RETRY_FAILED(140003, "本地消息重试执行失败"),
    LOCAL_MESSAGE_RETRY_LIMIT_EXCEEDED(140004, "本地消息重试次数已达上限"),

    // ------------ 15xxx Offer 录用邀请错误码 ------------
    OFFER_NOT_FOUND(150001, "Offer 不存在"),
    OFFER_STATUS_INVALID(150002, "Offer 状态不合法"),
    OFFER_VERSION_CONFLICT(150003, "Offer 版本冲突，请刷新后重试"),
    OFFER_EXPIRED(150004, "Offer 已过期"),
    OFFER_ALREADY_EXISTS(150005, "该投递已存在有效 Offer"),
    OFFER_IDEMPOTENCY_KEY_CONFLICT(150006, "幂等键冲突，请勿重复提交不同参数"),
    OFFER_NOT_SENT_YET(150007, "Offer 尚未发送，无法执行该操作"),
    OFFER_ALREADY_DECIDED(150008, "Offer 已被接受或拒绝"),
    OFFER_DECISION_CONFLICT(150009, "Offer 决策冲突，可能已被并发操作处理"),
    OFFER_WITHDRAWN(150010, "Offer 已被撤回"),
    ;

    private final Integer code;
    private final String message;

    ErrorCode(Integer code, String message) {
        this.code = code;
        this.message = message;
    }

}
